[window]
# https://alacritty.org/config-alacritty.html#s11
decorations = "None"
# decorations = "Full" # default

[font]
size = 14

[font.normal]
# family = "Fira Code Light"
family = "FiraCode Nerd Font Mono"

[general]
# https://github.com/alacritty/alacritty-theme/blob/master/README.md
import = [
    # "~/.config/alacritty/themes/themes/github_light.toml"
    # "~/.config/alacritty/themes/themes/github_dark.toml"

    # "~/.config/alacritty/themes/themes/ayu_light.toml"
    # "~/.config/alacritty/themes/themes/ayu_dark.toml"

    # "~/.config/alacritty/themes/themes/tango_dark.toml"

    "~/.config/alacritty/themes/themes/dark_pastel.toml"
]
