# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

font:
  size: 12
  normal:
    family: Fira Code

# # Solaried Light
# colors:
#   primary:
#     background: '#fdf6e3' # base3
#     foreground: '#657b83' # base00
#   normal:
#     black:   '#073642' # base02
#     red:     '#dc322f' # red
#     green:   '#859900' # green
#     yellow:  '#b58900' # yellow
#     blue:    '#268bd2' # blue
#     magenta: '#d33682' # magenta
#     cyan:    '#2aa198' # cyan
#     white:   '#eee8d5' # base2
#   bright:
#     black:   '#002b36' # base03
#     red:     '#cb4b16' # orange
#     green:   '#586e75' # base01
#     yellow:  '#657b83' # base00
#     blue:    '#839496' # base0
#     magenta: '#6c71c4' # violet
#     cyan:    '#93a1a1' # base1
#     white:   '#fdf6e3' # base3

# Atom One Light
colors:
  primary:
    background: '0xf8f8f8'
    foreground: '0x2a2b33'

  normal:
    black:   '0x000000'
    red:     '0xde3d35'
    green:   '0x3e953a'
    yellow:  '0xd2b67b'
    blue:    '0x2f5af3'
    magenta: '0xa00095'
    cyan:    '0x3e953a'
    white:   '0xbbbbbb'

  bright:
    black:   '0x000000'
    red:     '0xde3d35'
    green:   '0x3e953a'
    yellow:  '0xd2b67b'
    blue:    '0x2f5af3'
    magenta: '0xa00095'
    cyan:    '0x3e953a'
    white:   '0xffffff'
