# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

font:
  size: 10
  normal:
    family: Fira Code

# Solaried Light
colors:
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3
# 
# # # Atom One Light
# # colors:
# #   primary:
# #     background: '0xf8f8f8'
# #     foreground: '0x2a2b33'
# # 
# #   normal:
# #     black:   '0x000000'
# #     red:     '0xde3d35'
# #     green:   '0x3e953a'
# #     yellow:  '0xd2b67b'
# #     blue:    '0x2f5af3'
# #     magenta: '0xa00095'
# #     cyan:    '0x3e953a'
# #     white:   '0xbbbbbb'
# # 
# #   bright:
# #     black:   '0x000000'
# #     red:     '0xde3d35'
# #     green:   '0x3e953a'
# #     yellow:  '0xd2b67b'
# #     blue:    '0x2f5af3'
# #     magenta: '0xa00095'
# #     cyan:    '0x3e953a'
# #     white:   '0xffffff'


# # Colors (Night Owlish Light)
# colors:
#   bright:
#     black: '#7a8181'
#     blue: '#5ca7e4'
#     cyan: '#00c990'
#     green: '#49d0c5'
#     magenta: '#697098'
#     red: '#f76e6e'
#     white: '#989fb1'
#     yellow: '#dac26b'
#   cursor:
#     cursor: '#403f53'
#     text: '#fbfbfb'
#   normal:
#     black: '#011627'
#     blue: '#4876d6'
#     cyan: '#08916a'
#     green: '#2aa298'
#     magenta: '#403f53'
#     red: '#d3423e'
#     white: '#7a8181'
#     yellow: '#daaa01'
#   primary:
#     background: '#ffffff'
#     foreground: '#403f53'
#   selection:
#     background: '#f2f2f2'
#     text: '#403f53'
