#!/bin/sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi
(
	userConfiguredPath=$( $SHELL -c 'echo $PATH' )
	[ -z "$userConfiguredPath" ] && userConfiguredPath=$PATH
	#echo $userConfiguredPath > /tmp/dmenu_run-userConfiguredPath
	IFS=:
	if stest -dqr -n "$cache" $userConfiguredPath; then
		stest -flx $userConfiguredPath | sort -u | tee "$cache" | dmenu "$@"
	else
		dmenu "$@" < "$cache"
	fi

) |  ${SHELL:-"/bin/sh"} &
